version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: npm run test
      - run:
          name: exit with 1
          command: |
            sh ./simple_script.sh
