version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python
    steps:
      - run:
          command: |
            export TEST_VAR='hello'
            print $TEST_VAR
workflows:
  version: 2
  btd:
    jobs:
    - build
