version: 2.1
orbs:
  slack: circleci/slack@3.4.1
jobs:
  build:
    docker:
      - image: circleci/python
    steps:
      - slack/notify:
          channel: T02519B3Z
          color: '#42e2f4'
          mentions: 'DN1KTNY2E'
          message: This is a custom message notification
          webhook: https://hooks.slack.com/services/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
          author_name: $CIRCLE_USERNAME
      - run:
          command: |
            echo "hello world~"
            exit 1
workflows:
  version: 2
  btd:
    jobs:
    - build
