version: 2.1
orbs:
  slack: circleci/slack@3.4.1
jobs:
  build:
    docker:
      - image: circleci/python
    steps:
      - slack/notify:
          color: '#42e2f4'
          message: This is a custom message notification
          webhook: 'https://hooks.slack.com/services/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'
          author_name: $CIRCLE_USERNAME
      - run:
          command: |
            echo "hello world~"
            exit 1
workflows:
  version: 2
  btd:
    jobs:
    - build
